artifacts:
  secondary-artifacts:
    AppArtifact:
      files:
        - 'dist/**/*'
      base-directory: .
    DockerArtifact:
      files:
        - 'imagedefinitions.json'
      base-directory: .
