version: 0.2

env:
  exported-variables:
    - IMAGE_TAG
    - BUILD_VERSION

phases:
  build:
    commands:
      - export IMAGE_TAG=$(git rev-parse --short HEAD)
      - export BUILD_VERSION="1.0.${CODEBUILD_BUILD_NUMBER}"
