cache:
  paths:
    - '/root/.cache/pip/**/*'         # Python
    - 'node_modules/**/*'              # Node.js
    - '/root/.m2/**/*'                 # Maven (Java)
    - '/root/.gradle/**/*'             # Gradle (Java)
    - '/root/.npm/**/*'                # npm
